### ISSUE TITLE
Skip invalid phone numbers

### ISSUE THREAD

**Issue by Thuderduds** [sjmf/bulk-sms#2]
The program stops when it finds an invalid phone number. It would be better if it keeps going and then just share a list of invalid numbers.

**Comment by sjmf** [comment]
Sounds good. If you can submit and test a PR I'm happy to merge it.

**Comment by sjmf** [comment]
I unfortunately don't have time to add this functionality myself, sorry. If you want to submit a Pull Request, I'd be very happy to merge it.
