### ISSUE TITLE
Is scheduling send-time possible?

### ISSUE THREAD

**Issue by Nestak2** [sjmf/bulk-sms#3]
This looks like a really helpful repo, but I also need to specify the time when each SMS needs to be sent. Is this doable with the code provided in the repo? Is it else possible in twilio with python code? Are there alternatives to twilio that offer easy SMS scheduling? Tnx

**Comment by sjmf** [comment]
There are definitely ways of calling this code on a timer.

If it's a regularly scheduled task, a [cronjob](https://en.wikipedia.org/wiki/Cron) might do it? You could set up and use something like [Jenkins](https://stackoverflow.com/questions/12472645/how-do-i-schedule-jobs-in-jenkins) if you want a UI.

Looking at the Twilio [API docs](https://www.twilio.com/docs/sms) I don't think that function exists directly in Twilio's API. You'd have to script something around it to run on your end.

If you need a more arbitrary set of times, e.g. sending on a list of timestamps, the simplest solution might be just to write some wrapper code in Python which loads the list of times, waits until the first one, then runs the sending task?

```
#!/usr/bin/python
from datetime import datetime
import time

with open('times.txt') as file:
    times = [datetime.strptime(t, '%Y-%m-%d %H:%M:%S') for t in file.read().split('\n')]

while times:
    now = datetime.today()
    until = times.pop(0)
    seconds = (until-now).total_seconds()
    
    if until > now:
        print('sleeping for {} seconds'.format(seconds))
        time.sleep(seconds)

        send_sms()
```

This assumes you've refactored the code in the repo under a method called send_sms()

Where times.txt contains:
```
2020-08-13 21:15:00
2020-08-13 21:16:00
2020-08-13 21:17:00
```
