### ISSUE TITLE
twilio.base.exceptions.TwilioRestException [Issue via email]

### ISSUE THREAD

**Issue by sjmf** [sjmf/bulk-sms#6]
The following issue was received via email. Please note the preferred way to receive issues is via GitHub.
 
> Traceback (most recent call last):
>   File "C:\PycharmP\Send BulkSms\bulk-sms-master\sms.py", line 53, in <module>
>     message = client.messages.create(to=num, from_=from_num, body=sms)
>   File "C:\Python39\lib\site-packages\twilio\rest\api\v2010\account\message\__init__.py", line 88, in create
>     payload = self._version.create(method='POST', uri=self._uri, data=data, )
>   File "C:\Python39\lib\site-packages\twilio\base\version.py", line 205, in create
>     raise self.exception(method, uri, response, 'Unable to create record')
> twilio.base.exceptions.TwilioRestException: HTTP 404 error: Unable to create record: The requested resource /2010-04-01/Accounts/<???????????????????>/Messages.json was not found

**Comment by sjmf** [comment]
I can reproduce this error. I believe your Twilio account SID is incorrect.

Please make sure you have removed the < > angle brackets from your Twilio account credentials. These should not be included. The code should look like:

account_sid = "ABCDEF01234567890"

I hope this solves your problem.

For future interest, raising a GitHub issue rather than emailing is the best way to help others who have the same problem as you.

**Comment by kurtfrancisco** [comment]
i get same error

I checked my SID and auth token

not sure


here is my error:

```
Traceback (most recent call last):
  File "C:\Users\kfprg\Desktop\Twilio\bulk-sms-master\sms.py", line 56, in <module>
    message = client.messages.create(to=num, from_=from_num, body=sms)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kfprg\AppData\Local\Programs\Python\Python311\Lib\site-packages\twilio\rest\api\v2010\account\message\__init__.py", line 103, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data, )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kfprg\AppData\Local\Programs\Python\Python311\Lib\site-packages\twilio\base\version.py", line 205, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException:
←[31m←[49mHTTP Error←[0m ←[37m←[49mYour request was:←[0m

←[36m←[49mPOST /Accounts/ACc5c989eb27b5ebb9553b67e6a52c5f39/Messages.json←[0m

←[37m←[49mTwilio returned the following information:←[0m

←[34m←[49mUnable to create record: A 'To' phone number is required.←[0m

←[37m←[49mMore information may be available here:←[0m

←[34m←[49mhttps://www.twilio.com/docs/errors/21604←[0maceback (most recent call last):
  File "C:\Users\kfprg\Desktop\Twilio\bulk-sms-master\sms.py", line 56, in <module>
    message = client.messages.create(to=num, from_=from_num, body=sms)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kfprg\AppData\Local\Programs\Python\Python311\Lib\site-packages\twilio\rest\api\v2010\account\message\__init__.py", line 103, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data, )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kfprg\AppData\Local\Programs\Python\Python311\Lib\site-packages\twilio\base\version.py", line 205, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException:
←[31m←[49mHTTP Error←[0m ←[37m←[49mYour request was:←[0m

←[36m←[49mPOST /Accounts/ACc5c989eb27b5ebb9553b67e6a52c5f39/Messages.json←[0m

←[37m←[49mTwilio returned the following information:←[0m

←[34m←[49mUnable to create record: The 'To' number 1523839805 is not a valid phone number.←[0m

←[37m←[49mMore information may be available here:←[0m

←[34m←[49mhttps://www.twilio.com/docs/errors/21211←[0m
```

**Comment by sjmf** [comment]
Hi @kurtfrancisco.

This is not the same error. The error from this issue #6 was:
```
twilio.base.exceptions.TwilioRestException: HTTP 404 error: Unable to create record: 
The requested resource /2010-04-01/Accounts/<???????????????????>/Messages.json was not found
```

Your error is:
```
twilio.base.exceptions.TwilioRestException: HTTP Error 
Your request was:
POST /Accounts/ACc5c989eb27b5ebb9553b67e6a52c5f39/Messages.json

Twilio returned the following information:
Unable to create record: The 'To' number 1523839805 is not a valid phone number.

More information may be available here:
https://www.twilio.com/docs/errors/21211
```
Your `participants.csv` file containing your contacts includes an invalid telephone number, `1523839805`. Either you have missed the `+` symbol at the start of the number for an international dialing code, or the number does not exist.

Please visit the link that your error message is referring you to: [https://www.twilio.com/docs/errors/21211](https://www.twilio.com/docs/errors/21211) for assistance with this error. 

You can handle this error by adding a `try/except` statement around the `send` function on line 55, to catch `twilio.base.exceptions.TwilioRestException` as follows:

```python
    # Send the messages
    for num in numbers:
        # Send the sms text to the number from the CSV file:
        print("Sending to " + num)
        try:
            message = client.messages.create(to=num, from_=from_num, body=sms)
        except TwilioRestException as e:
            print(e)
        time.sleep(TIMEOUT_SECONDS)
 ```
Also import the relevant exception at the top of the file:

```python
from twilio.base.exceptions import TwilioRestException
```
See the [python `except` documentation](https://docs.python.org/3/tutorial/errors.html#handling-exceptions) for more information on error handling.

**Comment by kurtfrancisco** [comment]
can i use python 3.11

or does it have to be python 3.6?

**Comment by sjmf** [comment]
AFAIK there should be no problem with that. You're welcome to try it and see.
